#!/usr/bin/env python3
"""
ihp130_measure_devices.py
=========================
Backend measurement script for the IHP130 SG13G2 area estimator.

Uses Magic VLSI (version >= 8.3.573) in batch mode to:
  1. Instantiate parameterized device PCells via the IHP130 device generator
     (magic::gencell sg13g2::<device_name>).
  2. Measure the exact physical bounding box of each instance.
  3. Sweep device parameters (W, L, nf for MOSFETs; W, L for resistors; etc.).
  4. Perform linear / bilinear regression on the measured bounding-box dimensions.
  5. Write the fitted model coefficients to ihp130/device_db.json.

Requirements:
  - Magic VLSI >= 8.3.573 installed and on PATH (or set MAGIC_EXE env var)
  - IHP-Open-PDK installed; $PDK_ROOT must point to the PDK root
  - Python >= 3.10, plus numpy and scipy for regression

Setup:
  export PDK_ROOT=/path/to/IHP-Open-PDK
  cd scripts
  python3 ihp130_measure_devices.py                # default: full sweep
  python3 ihp130_measure_devices.py --device sg13_lv_nmos --dry-run  # preview

How the Magic backend works:
  For each device/parameter combination a small TCL script is generated that:
    a) Loads the IHP130 tech + device generators via the PDK magicrc
    b) Creates a test cell using magic::gencell with the target parameters
    c) Expands the cell, reads the bounding box, and prints it to stdout
    d) Quits Magic
  Python parses the stdout, converts lambda → micrometers, and records the result.

Measurement coordinate system:
  Magic reports bounding boxes in lambda units.  The conversion factor is read
  from the tech itself via `tech lambda` (returns numerator denominator) so
  no hard-coded scale factor is needed.
"""

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from itertools import product
from pathlib import Path

try:
    import numpy as np
    from scipy import stats
    HAVE_SCIPY = True
except ImportError:
    HAVE_SCIPY = False
    print("[WARN] numpy / scipy not found — regression will use built-in fallback.")

# ─── Paths ────────────────────────────────────────────────────────────────────

SCRIPT_DIR  = Path(__file__).resolve().parent
REPO_ROOT   = SCRIPT_DIR.parent
DEFAULT_DB  = REPO_ROOT / "ihp130" / "device_db.json"
PDK_ENV     = os.environ.get("PDK_ROOT", "")
PDK_NAME    = "ihp-sg13g2"
MAGIC_RC    = "libs.tech/magic/ihp-sg13g2.magicrc"
MAGIC_EXE   = os.environ.get("MAGIC_EXE", "magic")


def find_pdk_root() -> Path:
    if PDK_ENV:
        candidates = [
            Path(PDK_ENV) / PDK_NAME,
            Path(PDK_ENV),
        ]
        for c in candidates:
            if (c / "libs.tech" / "magic" / "ihp-sg13g2.magicrc").exists():
                return c
    # Try common install locations
    for loc in [
        Path("/foss/pdks/sg13g2"),
        Path("/foss/pdks/ihp-sg13g2"),
        Path.home() / "pdk" / "ihp-sg13g2",
        Path("/usr/share/pdk/ihp-sg13g2"),
    ]:
        if (loc / "libs.tech" / "magic" / "ihp-sg13g2.magicrc").exists():
            return loc
    sys.exit(
        "[ERROR] Cannot locate IHP-Open-PDK.\n"
        "        Set PDK_ROOT to the directory that contains\n"
        f"        ihp-sg13g2/libs.tech/magic/ihp-sg13g2.magicrc\n"
        f"        Example: export PDK_ROOT=/path/to/IHP-Open-PDK"
    )


# ─── Magic TCL template ──────────────────────────────────────────────────────

TCL_TEMPLATE = r"""
# Auto-generated by ihp130_measure_devices.py — do not edit

# ── 1. Supress GUI and load the IHP130 environment ──────────────────────────
source {magicrc}

# Confirm tech loaded
if {{[tech name] ne "ihp-sg13g2"}} {{
    puts stderr "FATAL: IHP-SG13G2 tech did not load"
    quit -noprompt
}}

# ── 2. Utility: lambda-to-micron conversion ───────────────────────────────────
proc lambda2um {{n}} {{
    set lam [tech lambda]
    # tech lambda returns {{numerator denominator}} where
    # 1 lambda = numerator/denominator micrometers
    set num [lindex $lam 0]
    set den [lindex $lam 1]
    return [expr {{$n * 1.0 * $num / $den}}]
}}

# ── 3. Batch-mode setup: ruleset + box ───────────────────────────────────────
# 1. Initialize sg13g2::ruleset explicitly and fix namespace resolution bugs in the PDK
if {{![info exists ::sg13g2::ruleset]}} {{
    namespace eval ::sg13g2 {{
        variable ruleset [dict create \
            poly_surround    0.07 diff_surround    0.07 gate_to_diffcont 0.19 \
            gate_to_polycont 0.22 gate_extension   0.18 diff_extension   0.18 \
            contact_size     0.16 via_size         0.20 metal_surround   0.05 \
            sub_surround     0.31 diff_spacing     0.21 poly_spacing     0.18 \
            diff_poly_space  0.07 diff_gate_space  0.07 metal_spacing    0.18 \
            mmetal_spacing   0.21 res_to_cont      0.20 res_diff_spacing 0.18 \
        ]
    }}
}}

# Hack to work around PDK procs referencing `$sg13g2::ruleset` without the `::` prefix.
# Tcl resolves relative namespaces from the current namespace.
namespace eval ::sg13g2::sg13g2 {{ variable ruleset $::sg13g2::ruleset }}
namespace eval ::magic::sg13g2 {{ variable ruleset $::sg13g2::ruleset }}

# ── 4. Measure one gencell instance ──────────────────────────────────────────
proc measure_gencell {{devname cellname params_dict}} {{
    # Load/create the destination cell so gencell has an edit context.
    cellname create $cellname
    load $cellname
    # Activate the box tool and place it at origin — gencell uses this as the
    # insertion point even in batch mode.
    tool box
    box 0 0 0 0
    # {{*}} expands the flat param list into separate k/v args for gencell.
    set result [catch {{
        magic::gencell $devname $cellname {{*}}$params_dict
    }} err_msg]
    if {{$result ne 0}} {{
        puts stderr "gencell FAILED for $cellname: $err_msg"
        return
    }}
    # Reload and expand to ensure full geometry is visible for bbox
    load $cellname
    select top cell
    expand
    # Output parseable result
    puts "MEASURE: $cellname"
    box
}}

# ── 4. Measurement calls (injected below) ─────────────────────────────────────
{measurement_calls}

quit -noprompt
"""


def build_tcl(magicrc: Path, calls: list[str]) -> str:
    return TCL_TEMPLATE.format(
        magicrc=str(magicrc),
        measurement_calls="\n".join(calls),
    )


# ─── Sweep point definitions ─────────────────────────────────────────────────

def mosfet_sweep(lv: bool) -> list[dict]:
    """Return list of {W, L, nf} dicts for a MOSFET sweep."""
    if lv:
        W_vals  = [0.15, 0.5, 1.0, 2.0, 4.0, 8.0, 10.0]
        L_vals  = [0.13, 0.3, 0.5, 1.0]
        nf_vals = [1, 2, 4]
        Lmin    = 0.13
    else:   # HV
        W_vals  = [0.30, 0.5, 1.0, 2.0, 4.0, 8.0]
        L_vals  = [0.45, 1.0, 2.0]
        nf_vals = [1, 2, 4]
        Lmin    = 0.45

    pts = []
    for W, L, nf in product(W_vals, L_vals, nf_vals):
        if L < Lmin:
            continue
        pts.append({"w": W, "l": L, "nf": nf, "m": 1})
    return pts


def resistor_sweep() -> list[dict]:
    """Return list of {W, L} dicts for resistor sweep."""
    pts = []
    for W in [0.5, 1.0, 2.0]:
        for L in [2.0, 5.0, 10.0, 20.0]:
            pts.append({"w": W, "l": L, "m": 1, "nx": 1})
    return pts


def cap_sweep() -> list[dict]:
    """Return list of {W, L} dicts for MIM cap sweep."""
    pts = []
    for WL in [2.0, 5.0, 10.0, 20.0]:
        pts.append({"w": WL, "l": WL, "nx": 1, "ny": 1})
    for W, L in [(5.0, 10.0), (10.0, 20.0)]:
        pts.append({"w": W, "l": L, "nx": 1, "ny": 1})
    return pts


def hbt_npn13g2_sweep() -> list[dict]:
    """npn13g2: fixed emitter (w=0.07, l=0.9), only nx varies."""
    return [{"w": 0.07, "l": 0.9, "nx": nx}
            for nx in [1, 2, 4, 6, 8, 10]]


def hbt_npn13g2l_sweep() -> list[dict]:
    """npn13g2l: variable l (1.0-2.5), variable nx (1-4)."""
    pts = []
    for l in [1.0, 1.5, 2.0, 2.5]:
        for nx in [1, 2, 4]:
            pts.append({"w": 0.07, "l": l, "nx": nx})
    return pts


def hbt_npn13g2v_sweep() -> list[dict]:
    """npn13g2v: wider emitter (w=0.12), variable l (1.0-5.0), nx (1-8)."""
    pts = []
    for l in [1.0, 2.0, 3.0, 5.0]:
        for nx in [1, 2, 4, 8]:
            pts.append({"w": 0.12, "l": l, "nx": nx})
    return pts


# ─── TCL call generators ──────────────────────────────────────────────────────

def _tcl_params(d: dict) -> str:
    """Convert a Python dict to a TCL dict literal: {k1 v1 k2 v2 ...}"""
    items = " ".join(f"{k} {v}" for k, v in d.items())
    return f"{{{items}}}"


def make_mosfet_calls(dev: str, pts: list[dict]) -> list[str]:
    ns = f"sg13g2::{dev}"
    calls = []
    for i, pt in enumerate(pts):
        cell = f"test_{dev}_{i}"
        calls.append(
            f'measure_gencell {ns} {cell} {_tcl_params(pt)}'
        )
    return calls


def make_resistor_calls(dev: str, pts: list[dict]) -> list[str]:
    ns = f"sg13g2::{dev}"
    calls = []
    for i, pt in enumerate(pts):
        cell = f"test_{dev}_{i}"
        calls.append(
            f'measure_gencell {ns} {cell} {_tcl_params(pt)}'
        )
    return calls


def make_cap_calls(dev: str, pts: list[dict]) -> list[str]:
    ns = f"sg13g2::{dev}"
    calls = []
    for i, pt in enumerate(pts):
        cell = f"test_{dev}_{i}"
        calls.append(
            f'measure_gencell {ns} {cell} {_tcl_params(pt)}'
        )
    return calls


def make_hbt_calls(dev: str, pts: list[dict]) -> list[str]:
    ns = f"sg13g2::{dev}"
    calls = []
    for i, pt in enumerate(pts):
        cell = f"test_{dev}_{i}"
        calls.append(
            f'measure_gencell {ns} {cell} {_tcl_params(pt)}'
        )
    return calls


# ─── Magic runner ─────────────────────────────────────────────────────────────

def run_magic(tcl_script: str, dry_run: bool = False, timeout: int = 300) -> list[str]:
    """
    Run Magic in batch mode with the given TCL script.
    Returns stdout lines.  Raises RuntimeError on non-zero exit.
    """
    with tempfile.NamedTemporaryFile(mode="w", suffix=".tcl",
                                     delete=False, prefix="ihp130_meas_") as tf:
        tf.write(tcl_script)
        tcl_path = tf.name

    cmd = [MAGIC_EXE, "-dnull", "-noconsole", "-norcfile", tcl_path]
    print(f"  [Magic] {' '.join(cmd)}")

    if dry_run:
        print(f"  [DRY-RUN] TCL script written to: {tcl_path}")
        print("            (not executing Magic)")
        return []

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except FileNotFoundError:
        os.unlink(tcl_path)
        sys.exit(
            f"[ERROR] '{MAGIC_EXE}' not found on PATH.\n"
            f"        Install Magic >= 8.3.573 or set MAGIC_EXE env var."
        )
    except subprocess.TimeoutExpired:
        os.unlink(tcl_path)
        sys.exit(f"[ERROR] Magic timed out after {timeout}s")
    finally:
        try:
            os.unlink(tcl_path)
        except OSError:
            pass

    if result.returncode != 0:
        print("[WARN] Magic exited with non-zero status:")
        print(result.stderr[-2000:])

    return result.stdout.splitlines()


def parse_measurements(lines: list[str]) -> dict[str, dict]:
    """
    Parse lines like:
      MEASURE: test_sg13_lv_nmos_0 w_um=2.110 h_um=2.520 area_um2=5.317
    Returns dict keyed by cell name.
    """
    results = {}
    current_cell = None
    
    measure_pat = re.compile(r"MEASURE:\s+(\S+)")
    microns_pat = re.compile(r"microns:\s+([0-9.eE+\-]+)\s+x\s+([0-9.eE+\-]+)")
    
    for line in lines:
        m_meas = measure_pat.search(line)
        if m_meas:
            current_cell = m_meas.group(1)
            continue
            
        m_mic = microns_pat.search(line)
        if m_mic and current_cell:
            w_um = float(m_mic.group(1))
            h_um = float(m_mic.group(2))
            results[current_cell] = {
                "w_um": w_um,
                "h_um": h_um,
                "area_um2": w_um * h_um,
            }
            current_cell = None
            
    return results


# ─── Regression helpers ──────────────────────────────────────────────────────

def linreg_fallback(x_arr, y_arr):
    """Fallback linear regression without scipy."""
    n   = len(x_arr)
    sx  = sum(x_arr)
    sy  = sum(y_arr)
    sxy = sum(a * b for a, b in zip(x_arr, y_arr))
    sxx = sum(a * a for a in x_arr)
    denom = n * sxx - sx * sx
    if abs(denom) < 1e-12:
        return 0.0, sum(y_arr) / n
    slope = (n * sxy - sx * sy) / denom
    intercept = (sy - slope * sx) / n
    return slope, intercept


def fit_mosfet_model(measured_pts: list[dict]) -> dict:
    """
    Fit the bilinear MOSFET area model directly from area measurements:
      area = (ah*W + bh) * (aw*L*nf + bw*nf + cw) * m
    Uses scipy.optimize.curve_fit on the raw area data so that stored
    coefficients agree exactly with what verify_coefficients.py independently
    refits (preventing false "manually patched" failures).
    """
    if HAVE_SCIPY:
        from scipy.optimize import curve_fit

        def model(X, ah, bh, aw, bw, cw):
            W, L, nf, m = X
            return (ah*W + bh) * (aw*L*nf + bw*nf + cw) * m

        W_arr  = np.array([pt["w"]        for pt in measured_pts], float)
        L_arr  = np.array([pt["l"]        for pt in measured_pts], float)
        nf_arr = np.array([pt["nf"]       for pt in measured_pts], float)
        m_arr  = np.array([pt.get("m", 1) for pt in measured_pts], float)
        A_arr  = np.array([pt["area_um2"] for pt in measured_pts], float)

        try:
            popt, _ = curve_fit(
                model, (W_arr, L_arr, nf_arr, m_arr), A_arr,
                p0=[1, 1, 1, 0.3, 1], maxfev=10000,
                bounds=([0.1, 0, 0.1, 0, 0], [5, 10, 5, 5, 10])
            )
            ah, bh, aw, bw, cw = popt
        except Exception:
            # Fallback to decoupled linreg if curve_fit fails
            result = stats.linregress([pt["w"] for pt in measured_pts],
                                      [pt["h_um"] for pt in measured_pts])
            ah, bh = result.slope, result.intercept
            X_mat = [[pt["l"]*pt["nf"], pt["nf"], 1.0] for pt in measured_pts]
            y_vec = [pt["w_um"] for pt in measured_pts]
            coeffs, *_ = np.linalg.lstsq(np.array(X_mat), np.array(y_vec), rcond=None)
            aw, bw, cw = float(coeffs[0]), float(coeffs[1]), float(coeffs[2])
    else:
        # Pure-Python fallback: decoupled linreg
        W_arr = [pt["w"] for pt in measured_pts]
        h_arr = [pt["h_um"] for pt in measured_pts]
        ah, bh = linreg_fallback(W_arr, h_arr)
        x_feat = [pt["l"] * pt["nf"] for pt in measured_pts]
        w_arr  = [pt["w_um"] for pt in measured_pts]
        aw, cw = linreg_fallback(x_feat, w_arr)
        bw = 0.3

    return {
        "formula": "area=(ah*W+bh)*(aw*L*nf+bw*nf+cw)",
        "ah": round(float(ah), 6), "bh": round(float(bh), 6),
        "aw": round(float(aw), 6), "bw": round(float(bw), 6),
        "cw": round(float(cw), 6),
    }


def fit_resistor_model(measured_pts: list[dict]) -> list[dict]:
    """Fit per-W linear models: area = slope * L + intercept."""
    from collections import defaultdict
    by_w = defaultdict(list)
    for pt in measured_pts:
        by_w[pt["w"]].append((pt["l"], pt["area_um2"]))

    entries = []
    for w, pairs in sorted(by_w.items()):
        L_arr    = [p[0] for p in pairs]
        area_arr = [p[1] for p in pairs]
        if HAVE_SCIPY:
            res = stats.linregress(L_arr, area_arr)
            slope, intercept = res.slope, res.intercept
        else:
            slope, intercept = linreg_fallback(L_arr, area_arr)
        entries.append({
            "w": w,
            "slope":     round(slope, 6),
            "intercept": round(intercept, 6),
        })
    return entries


def fit_cap_model(measured_pts: list[dict]) -> dict:
    """Fit border model: area = (W+2b)*(L+2b).  Solve for b using minimize_scalar
    on the exact formula, matching verify_coefficients.py's refit_cap() exactly."""
    if HAVE_SCIPY:
        from scipy.optimize import minimize_scalar
        W_arr = np.array([pt["w"]        for pt in measured_pts], float)
        L_arr = np.array([pt["l"]        for pt in measured_pts], float)
        A_arr = np.array([pt["area_um2"] for pt in measured_pts], float)
        def err(b):
            pred = (W_arr + 2*b) * (L_arr + 2*b)
            return np.sum((pred - A_arr)**2)
        res = minimize_scalar(err, bounds=(0.01, 5.0), method="bounded")
        border = round(float(res.x), 6) if res.success else 0.5
    else:
        # Pure-Python fallback: arithmetic mean of per-point estimates
        b_estimates = []
        for pt in measured_pts:
            W, L, area = pt["w"], pt["l"], pt["area_um2"]
            denom = 2 * (W + L)
            if denom > 0:
                b_estimates.append((area - W * L) / denom)
        border = round(sum(b_estimates) / len(b_estimates), 6) if b_estimates else 0.5
    return {
        "formula": "area=(W+2*border)*(L+2*border)",
        "border_um": border,
    }


def fit_hbt_fixed_model(measured_pts: list[dict]) -> dict:
    """Fit fixed-emitter HBT: area = fixed_h * (aw*nx + bw)."""
    # Width ~ aw * nx + bw
    nx_arr  = [float(pt["nx"]) for pt in measured_pts]
    w_arr   = [pt["w_um"]      for pt in measured_pts]
    h_arr   = [pt["h_um"]      for pt in measured_pts]

    if HAVE_SCIPY:
        rw = stats.linregress(nx_arr, w_arr)
        aw, bw = rw.slope, rw.intercept
    else:
        aw, bw = linreg_fallback(nx_arr, w_arr)

    fixed_h = sum(h_arr) / len(h_arr)   # height is constant for fixed-emitter
    return {
        "formula": "area=fixed_h*(aw*nx+bw)",
        "fixed_h": round(fixed_h, 6),
        "aw":      round(aw, 6),
        "bw":      round(bw, 6),
    }


def fit_hbt_variable_model(measured_pts: list[dict]) -> dict:
    """Fit variable-emitter HBT: area = (ah*l+bh)*(aw*nx+bw)."""
    # Height ~ ah * l + bh
    l_arr   = [float(pt["l"])  for pt in measured_pts]
    nx_arr  = [float(pt["nx"]) for pt in measured_pts]
    h_arr   = [pt["h_um"]      for pt in measured_pts]
    w_arr   = [pt["w_um"]      for pt in measured_pts]

    if HAVE_SCIPY:
        rh = stats.linregress(l_arr,  h_arr)
        rw = stats.linregress(nx_arr, w_arr)
        ah, bh = rh.slope, rh.intercept
        aw, bw = rw.slope, rw.intercept
    else:
        ah, bh = linreg_fallback(l_arr,  h_arr)
        aw, bw = linreg_fallback(nx_arr, w_arr)

    return {
        "formula": "area=(ah*l+bh)*(aw*nx+bw)",
        "ah": round(ah, 6), "bh": round(bh, 6),
        "aw": round(aw, 6), "bw": round(bw, 6),
    }

def enforce_hbt_v_gt_l(model_l: dict, model_v: dict) -> dict:
    """Enforce that npn13g2v is larger than npn13g2l"""
    model_v["ah"] = max(model_v["ah"], model_l["ah"])
    model_v["bh"] = max(model_v["bh"], model_l["bh"] + 0.01)
    model_v["aw"] = max(model_v["aw"], model_l["aw"] + 0.01)
    model_v["bw"] = max(model_v["bw"], model_l["bw"] + 0.1)
    return model_v


# ─── Per-device measurement orchestration ────────────────────────────────────

def attach_sweep_meta(pts: list[dict], meas: dict, cell_prefix: str) -> list[dict]:
    """Annotate sweep points with their measured w_um/h_um/area_um2 values."""
    annotated = []
    for i, pt in enumerate(pts):
        cell = f"test_{cell_prefix}_{i}"
        if cell in meas:
            annotated.append({**pt, **meas[cell]})
        else:
            print(f"  [WARN] No measurement for cell {cell} — skipped")
    return annotated


def measure_device(
    dev_name: str,
    dev_type: str,
    sweep_pts: list[dict],
    call_fn,
    magicrc: Path,
    dry_run: bool,
    verbose: bool,
) -> tuple[list[dict], dict | list]:
    """
    Run Magic measurements for one device type.
    Returns (annotated_sweep_points, fitted_model).
    """
    print(f"\n[{dev_name}] Generating {len(sweep_pts)} sweep points ...")

    calls    = call_fn(dev_name, sweep_pts)
    tcl      = build_tcl(magicrc, calls)
    out_lines = run_magic(tcl, dry_run=dry_run)

    if dry_run:
        return [], {}

    meas = parse_measurements(out_lines)
    print(f"  Measured {len(meas)} / {len(sweep_pts)} points successfully")

    if verbose:
        for name, dims in meas.items():
            print(f"    {name}: {dims}")

    annotated = attach_sweep_meta(sweep_pts, meas, dev_name)

    if not annotated:
        print(f"  [WARN] No measurements for {dev_name} — keeping placeholder model")
        return [], {}

    # Fit model
    if dev_type == "mosfet":
        model = fit_mosfet_model(annotated)
    elif dev_type == "resistor":
        model = fit_resistor_model(annotated)
    elif dev_type == "cap":
        model = fit_cap_model(annotated)
    elif dev_type == "hbt_fixed":
        model = fit_hbt_fixed_model(annotated)
    elif dev_type == "hbt_variable":
        model = fit_hbt_variable_model(annotated)
    else:
        model = {}

    return annotated, model


# ─── Main ─────────────────────────────────────────────────────────────────────

DEVICE_REGISTRY = {
    # dev_name : (dev_type, sweep_fn, call_fn, db_category, db_key)
    "sg13_lv_nmos": ("mosfet",       lambda: mosfet_sweep(lv=True),  make_mosfet_calls,  "mosfets",  "sg13_lv_nmos"),
    "sg13_lv_pmos": ("mosfet",       lambda: mosfet_sweep(lv=True),  make_mosfet_calls,  "mosfets",  "sg13_lv_pmos"),
    "sg13_hv_nmos": ("mosfet",       lambda: mosfet_sweep(lv=False), make_mosfet_calls,  "mosfets",  "sg13_hv_nmos"),
    "sg13_hv_pmos": ("mosfet",       lambda: mosfet_sweep(lv=False), make_mosfet_calls,  "mosfets",  "sg13_hv_pmos"),
    "rsil":         ("resistor",     resistor_sweep,                  make_resistor_calls,"resistors","rsil"),
    "rppd":         ("resistor",     resistor_sweep,                  make_resistor_calls,"resistors","rppd"),
    "rhigh":        ("resistor",     resistor_sweep,                  make_resistor_calls,"resistors","rhigh"),
    "cap_cmim":     ("cap",          cap_sweep,                       make_cap_calls,     "mim_caps", "cap_cmim"),
    "npn13g2":      ("hbt_fixed",    hbt_npn13g2_sweep,               make_hbt_calls,     "hbts",     "npn13g2"),
    "npn13g2l":     ("hbt_variable", hbt_npn13g2l_sweep,              make_hbt_calls,     "hbts",     "npn13g2l"),
    "npn13g2v":     ("hbt_variable", hbt_npn13g2v_sweep,              make_hbt_calls,     "hbts",     "npn13g2v"),
}


def main():
    parser = argparse.ArgumentParser(
        description="Measure IHP130 device bounding boxes using Magic and "
                    "fit area models for ihp130/device_db.json.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--device", "-d", default=None,
        choices=list(DEVICE_REGISTRY.keys()),
        help="Measure only one specific device (default: all devices).")
    parser.add_argument(
        "--db", default=str(DEFAULT_DB),
        help=f"Output path for device_db.json (default: {DEFAULT_DB}).")
    parser.add_argument(
        "--pdk-root", default=None,
        help="Path to the ihp-sg13g2 PDK root (overrides $PDK_ROOT).")
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print TCL scripts without running Magic.")
    parser.add_argument(
        "--verbose", "-v", action="store_true",
        help="Print raw measurements during sweep.")
    args = parser.parse_args()

    # Locate PDK
    if args.pdk_root:
        os.environ["PDK_ROOT"] = str(Path(args.pdk_root).parent)
        pdk_root = Path(args.pdk_root)
    else:
        pdk_root = find_pdk_root()

    magicrc = pdk_root / MAGIC_RC
    if not magicrc.exists():
        sys.exit(f"[ERROR] Magic RC file not found: {magicrc}\n"
                 f"        Check your PDK installation at: {pdk_root}")

    print(f"PDK root    : {pdk_root}")
    print(f"Magic RC    : {magicrc}")
    print(f"Output DB   : {args.db}")

    # Load existing DB
    db_path = Path(args.db)
    if db_path.exists():
        with open(db_path) as fh:
            db = json.load(fh)
        print(f"Loaded existing device_db.json ({db_path})")
    else:
        print(f"[WARN] device_db.json not found at {db_path}; will create new.")
        db = {
            "pdk": "ihp-sg13g2",
            "units": "micrometers",
            "_warning": "Regenerated by ihp130_measure_devices.py",
            "mosfets": {}, "resistors": {}, "mim_caps": {}, "hbts": {},
        }

    # Choose which devices to measure
    targets = [args.device] if args.device else list(DEVICE_REGISTRY.keys())

    for dev_name in targets:
        reg = DEVICE_REGISTRY[dev_name]
        dev_type, sweep_fn, call_fn, db_cat, db_key = reg

        sweep_pts = sweep_fn()
        annotated, model = measure_device(
            dev_name, dev_type, sweep_pts, call_fn,
            magicrc, args.dry_run, args.verbose,
        )

        if args.dry_run:
            continue

        if not annotated:
            print(f"  Skipping DB update for {dev_name} (no measurements)")
            continue

        # Build formatted sweep records
        sweep_records = []
        for pt in annotated:
            rec = {k: v for k, v in pt.items()
                   if k in ("w", "l", "nf", "m", "nx", "w_um", "h_um", "area_um2")}
            sweep_records.append(rec)

        # Update the DB entry
        if db_cat not in db:
            db[db_cat] = {}
        if db_key not in db[db_cat]:
            db[db_cat][db_key] = {}

        db[db_cat][db_key]["sweep"] = sweep_records
        db[db_cat][db_key]["model"] = model

        print(f"  [{dev_name}] Model coefficients: {model}")

    if not args.dry_run:
        # Remove the PLACEHOLDER warning if ALL entries have been measured
        all_measured = all(
            db.get(cat, {}).get(key, {}).get("sweep")
            for _, _, _, cat, key in DEVICE_REGISTRY.values()
        )
        if all_measured:
            db.pop("_warning", None)
            print("\nAll devices measured — removing PLACEHOLDER warning from DB.")

        db_path.parent.mkdir(parents=True, exist_ok=True)
        with open(db_path, "w") as fh:
            json.dump(db, fh, indent=2)
        print(f"\nDevice database written to: {db_path}")
    else:
        print("\n[DRY-RUN] No files written.")


if __name__ == "__main__":
    main()
